# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$docker\
$docker_context\
$python\
$golang\
$rust\
$lua\
$java\
$kotlin\
$terraform\
$git_branch\
$git_metrics\
$git_state\
$git_status\
$git_commit\
$helm\
$kubernetes\
$terraform\
$line_break\
$time\
$character"""

right_format = """
$shlvl\
$cmd_duration\
$container\
$jobs\
$hostname\
$status\
$username\
$battery"""

add_newline = true

[[battery.display]]
threshold = 15
style = 'bold red'

[character]
success_symbol = '[ï„ ](bold green) '
error_symbol = '[ï€](bold red) '

[jobs]
symbol = "ï€“ "

[status]
style = 'bg:black'
symbol = 'ğŸ”´ '
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[git_metrics]
disabled = false
added_style = 'bold green'
deleted_style = 'bold red'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '


[git_commit]
tag_disabled = false

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
untracked = '[ï…‚](cyan)'
modified = '[ï…‚](yellow)'
staged = '[ï…‚](green)'
renamed = '[ï…‚](purple)'
deleted = '[ï…‚](red)'
format = '$untracked$modified$staged$renamed$deleted '

[kubernetes]
disabled = false

[time]
disabled = false

[shlvl]
disabled = false
